import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const nimbusSans = localFont({
	variable: "--font-nimbus-sans",
	display: "swap",
	src: [
		{
			path: "./fonts/nimbus/nimbus-sans-light.woff2",
			weight: "300",
			style: "normal",
		},
		{
			path: "./fonts/nimbus/nimbus-sans-regular.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "./fonts/nimbus/nimbus-sans-bold.woff2",
			weight: "700",
			style: "normal",
		},
	],
})

const dotMatrix = localFont({
	variable: "--font-dot-matrix",
	display: "swap",
	src: [
		{
			path: "./fonts/dotmatrix/dot-matrix-regular.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "./fonts/dotmatrix/dot-matrix-bold.woff2",
			weight: "700",
			style: "normal",
		},
	],
})

const tiny = localFont({
	variable: "--font-tiny",
	display: "swap",
	src: [
		{
			path: "./fonts/tiny/tiny-60.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "./fonts/tiny/tiny-80.woff2",
			weight: "700",
			style: "normal",
		},
	],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${nimbusSans.className} ${dotMatrix.variable} ${tiny.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
